//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackDigital.Report {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReportResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReportResource() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlackDigital.Report.ReportResource", typeof(ReportResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a application/vnd.openxmlformats-package.core-properties+xml.
        /// </summary>
        internal static string ContentType_OpenXML_Core {
            get {
                return ResourceManager.GetString("ContentType_OpenXML_Core", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a application/vnd.openxmlformats-officedocument.extended-properties+xml.
        /// </summary>
        internal static string ContentType_OpenXML_Properties {
            get {
                return ResourceManager.GetString("ContentType_OpenXML_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a application/vnd.openxmlformats-package.relationships+xml.
        /// </summary>
        internal static string ContentType_OpenXML_Relationships {
            get {
                return ResourceManager.GetString("ContentType_OpenXML_Relationships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.
        /// </summary>
        internal static string ContentType_Spreadsheet {
            get {
                return ResourceManager.GetString("ContentType_Spreadsheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml.
        /// </summary>
        internal static string ContentType_Spreadsheet_Main {
            get {
                return ResourceManager.GetString("ContentType_Spreadsheet_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a application/vnd.openxmlformats-officedocument.spreadsheetml.sharedStrings+xml.
        /// </summary>
        internal static string ContentType_Spreadsheet_SharedStrings {
            get {
                return ResourceManager.GetString("ContentType_Spreadsheet_SharedStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml.
        /// </summary>
        internal static string ContentType_Spreadsheet_Sheet {
            get {
                return ResourceManager.GetString("ContentType_Spreadsheet_Sheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml.
        /// </summary>
        internal static string ContentType_Spreadsheet_Styles {
            get {
                return ResourceManager.GetString("ContentType_Spreadsheet_Styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;x:styleSheet xmlns:x=&quot;http://schemas.openxmlformats.org/spreadsheetml/2006/main&quot;&gt;
        ///   &lt;x:numFmts count=&quot;3&quot;&gt;
        ///      &lt;x:numFmt numFmtId=&quot;168&quot; formatCode=&quot;[h]:mm:ss;@&quot; /&gt;
        ///      &lt;x:numFmt numFmtId=&quot;165&quot; formatCode=&quot;d/m/yy\ h:mm;@&quot; /&gt;
        ///      &lt;x:numFmt numFmtId=&quot;164&quot; formatCode=&quot;[$-F400]h:mm:ss\ AM/PM&quot; /&gt;
        ///   &lt;/x:numFmts&gt;
        ///   &lt;x:fonts xmlns:x14ac=&quot;http://schemas.microsoft.com/office/spreadsheetml/2009/9/ac&quot; count=&quot;1&quot; x14ac:knownFonts=&quot;1&quot;&gt;
        ///      &lt;x:font&gt;
        ///         &lt;x:sz v [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Spreadsheet_Styles {
            get {
                return ResourceManager.GetString("Spreadsheet_Styles", resourceCulture);
            }
        }
    }
}
